# Uncomment this to use custom docker file => will take longer to open the workspace
# Also see: https://www.gitpod.io/docs/config-docker#custom-docker-image
# image:
#  file: .gitpod.Dockerfile 

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks: 
  - before: pyenv install 3.10.2 && pyenv global 3.10.2 && pip install poetry
    init: poetry install
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
#ports:
#  - port: 3000
#    onOpen: open-preview

# Configure Visual Studio Code 
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
