# Uncomment this to use custom docker file => will take longer to open the workspace
# Also see: https://www.gitpod.io/docs/config-docker#custom-docker-image
# image:
#  file: .gitpod.Dockerfile 

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks: 
  - before: pip install -r requirements.txt
    command: gp open notebook.ipynb

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
#ports:
#  - port: 3000
#    onOpen: open-preview

# Configure Visual Studio Code 
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
