# Uncomment this to use custom docker file => will take longer to open the workspace
# Also see: https://www.gitpod.io/docs/config-docker#custom-docker-image
# image:
#  file: .gitpod.Dockerfile 

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks: 
  - name: Install python dependencies
    before: pip install -r requirements.txt
    command: gp open notebook.ipynb

  - name: Start web server to show content of "public" folder
    init: python -m http.server 8080 public

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview

# Configure Visual Studio Code 
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
